server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        web: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
