server:
  port: 8888

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
            - Path=/register
          filters:
            - StripPrefix=0

        - id: produit-categorie-service
          uri: lb://produit-categorie-service
          predicates:
            - Path=/produits/**
            - Path=/categories/**
          filters:
            - name: JwtAuthFilter

        - id: commande-service
          uri: lb://commande-service
          predicates:
            - Path=/commandes/**
          filters:
            - name: JwtAuthFilter


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
